### ISSUE TITLE
dependencies tree is too deep for Windows

### ISSUE THREAD

**Issue by vankasteelj** [butterproviders/butter-provider-youtube#1]
it needs to be flattened somehow, windows can't handle that level of deepness.

**Comment by xaiki** [comment]
with npm 3.0 dependencies are flattened.

**Comment by z11h** [comment]
@vankasteelj try to run `npm install -g npm` (and/or `npm update -g npm`) so you can make sure that you are running npm > 3.0

:smile:

**Comment by xaiki** [comment]
@ZakariaRidouh NO, we do not want people to install our deps globally...

**Comment by z11h** [comment]
@xaiki umm, `npm install -g npm` does NOT install the deps globally, it only installs npm through npm so that it can update itself. This is similar to running `pip install --upgrade pip`. Sorry for the misunderstanding.

^_^

**Comment by vankasteelj** [comment]
Mmmh, https://github.com/butterproject/butter-desktop/commit/328576bb1d85a2b32e7cb26f884be209f8331c31#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R20
